public class OperatorExamples {
    /*
    // Assignment Operator (=)
    Integer x = 1;
    // Addition Assignment Operator (+=)
    x += 1;
    x += 5;
    x += 2;
    
    System.debug('x = ' + x);
    
    // Subtraction Assignment Operator (-=)
    x -= 1;
    System.debug('x = ' + x);
    
    
    // OR Assignment Operator Example (|=)
    Boolean isWeekend = true;
    Boolean isHoliday = true;
    
    Boolean dayOff = (isWeekend |= isHoliday);
    System.debug('Day Off? ' + dayOff);
    
    // AND Assignment Operator Example (&=)
    Boolean isWeekend = true;
    Boolean isHoliday = false;
    
    Boolean dayOff = (isWeekend &= isHoliday);
    System.debug('Day Off? ' + dayOff);
    
    // Ternary Operator ( ? : )
    Boolean b = (5 < 6) ? true : false;
    System.debug('b: ' + b);
    Boolean b2 = (10 < 6) ? true : false;
    System.debug('b2: ' + b2);
    
    // OR logical Operator ( || )
    System.debug('(true || true) ' + (true || true));
    System.debug('(false || true) ' + (false || true));
    System.debug('(false || false) ' + (false || false));
    
    // AND logical Operator ( && )
    System.debug('(true && true) ' + (true && true));
    System.debug('(false && true) ' + (false && true));
    System.debug('(false && false) ' + (false && false));
    
    // Equality Operator ( == )
    System.debug('(5 == 5) ' + (5 == 5));
    System.debug('(5 == 6) ' + (5 == 6));
    
    // Exact Equality Operator
    //Integer n1 = 5;
    //Integer n2 = 5;
    //System.debug(n1 === n2);
    Account a1 = new Account(Name='Matt');
    Account a2 = new Account(Name='Matt');
    System.debug('(a1 === a2) ' + (a1 === a2));
    
    Account a3 = new Account(Name='Matt');
    Account a4 = a3;
    System.debug('(a3 === a4) ' + (a3 === a4));
    
    // Prefixed Increment Operator (++x)
Integer x = 0;
System.debug('++x = ' + ++x);

// Postfixed Increment Operator (x++)
Integer x = 0;
System.debug('x++ = ' + x++);
System.debug('x: ' + x);

// Prefixed Decrement Operator (--x)
Integer x = 1;
System.debug('--x = ' + --x);

// Postfixed Increment Operator (x--)
Integer x = 1;
System.debug('x-- = ' + x--);
System.debug('x: ' + x);

Integer x = 0;
//(x++(++x + --x) + x++) + x--(x++(x--))
System.debug((x++ * ((++x == --x) ? 4 : 5) * x++) + (x-- * (x++ * x--)));
    
    
    
    */
        }